language: python
cache: pip
addons:
  firefox: "45.4.0esr"
os:
  - linux
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  # download and extract geckodrive to /usr/local/bin
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  - python xsstrike.py -u "https://public-firing-range.appspot.com/reflected/index.html" --crawl
  - echo "No" > input.txt && python xsstrike.py -u https://public-firing-range.appspot.com/reflected/parameter/body?q=query < input.txt
